# Etapa 1: Build del frontend React
FROM node:20-alpine AS frontend-build
WORKDIR /app
COPY onpe-frontend/package*.json ./
RUN npm ci
COPY onpe-frontend/ .
RUN npm run build

# Etapa 2: Nginx con el build + config de API Gateway
FROM nginx:1.25-alpine
COPY --from=frontend-build /app/dist /usr/share/nginx/html
COPY onpe-infra/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
