apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: onpe
data:
  default.conf: |
    upstream candidates_service {
        server candidates-service:8001;
    }
    upstream results_service {
        server results-service:8002;
    }
    upstream geography_service {
        server geography-service:8003;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location /api/candidatos/ {
            proxy_pass http://candidates_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/resultados/ {
            proxy_pass http://results_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/geo/ {
            proxy_pass http://geography_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
