apiVersion: apps/v1
kind: Deployment
metadata:
  name: geography-service
  namespace: onpe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geography-service
  template:
    metadata:
      labels:
        app: geography-service
    spec:
      containers:
        - name: geography-service
          image: onpe-geography-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8003
          env:
            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  name: onpe-config
                  key: MONGODB_URL
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: onpe-config
                  key: RABBITMQ_URL
            - name: RESULTS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: onpe-config
                  key: RESULTS_SERVICE_URL
            - name: PORT
              value: "8003"
          readinessProbe:
            httpGet:
              path: /api/geo/health
              port: 8003
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: geography-service
  namespace: onpe
spec:
  ports:
    - port: 8003
  selector:
    app: geography-service
